const STORAGE_KEY = 'site-language';

const translations = {
    ru: {
        lang: 'ru',
        title: 'Cyprus Total Service — SMM | Северный Кипр',
        description: 'SMM для премиум-недвижимости на Северном Кипре: съёмка, Reels/TikTok, Meta Ads и заявки на просмотр и бронь.',
        ogTitle: 'Cyprus Total Service — SMM | Северный Кипр',
        ogDescription: 'Контент, реклама и заявки для премиум-недвижимости на Северном Кипре. Съёмка, монтаж, ведение соцсетей и таргет.',
        nodes: [
            { selector: 'nav', attrs: { 'aria-label': 'Основная навигация' } },
            { selector: '[data-lang-switcher]', attrs: { 'aria-label': 'Переключение языка' } },
            { selector: '[data-nav-toggle]', attrs: { 'aria-label': 'Открыть меню' } },
            { selector: '[data-nav-menu] a[href="#section-about"]', text: 'Кто я' },
            { selector: '[data-nav-menu] a[href="#section-portfolio"]', text: 'Форматы' },
            { selector: '[data-nav-menu] a[href="#section-gallery"]', text: 'Видео' },
            { selector: '[data-nav-menu] a[href="#section-system"]', text: 'Услуги' },
            { selector: '[data-nav-menu] a[href="#section-packages"]', text: 'Пакеты' },
            { selector: '[data-nav-menu] a[href="#section-faq"]', text: 'FAQ' },
            { selector: '[data-nav-menu] a[href="#section-contact"]', text: 'Контакты' },
            { selector: 'header .leading-tight > span:first-child', text: 'Cyprus Total Service | SMM' },
            { selector: 'header .leading-tight > span:last-child', text: 'SMM · Северный Кипр' },
            { selector: '#section-main .tag', text: 'Cyprus Total Service · SMM' },
            { selector: '#section-main h1 span:first-child', html: 'Заявки на просмотр и&nbsp;бронь' },
            { selector: '#section-main h1 span:last-child', html: 'через короткий контент и&nbsp;рекламу на&nbsp;Северном Кипре' },
            { selector: '#section-main p.text-lg', html: 'Съёмка объектов, монтаж Reels / TikTok / Shorts, ведение соцсетей и&nbsp;таргет Meta. Один специалист вместо команды из&nbsp;3–4&nbsp;человек&nbsp;— от&nbsp;контента до&nbsp;лидов.' },
            { selector: '#section-main .btn-primary', text: 'Пакеты с рекламой' },
            { selector: '#section-main .btn-outline', text: 'Обсудить задачу' },
            { selector: '#section-main .mt-4.text-sm.text-slate-400', html: 'Для заявок на&nbsp;просмотр и&nbsp;бронь выгоднее пакеты «Контент&nbsp;+&nbsp;Реклама» или «Система продаж»' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .stat-pill__value', text: 'Контент' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .text-slate-400', html: 'съёмка и&nbsp;монтаж' },
            { selector: '#section-main .stat-pill:nth-of-type(2) .stat-pill__value', text: 'Реклама' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .stat-pill__value', text: 'Заявки' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .text-slate-400', html: 'лиды и&nbsp;брони' },
            { selector: '#section-main img[alt*="Премиум-вилла"]', attrs: { alt: 'Премиум-вилла — объект для Reels и TikTok' } },
            { selector: '#section-about .tag', text: 'Виктория · Cyprus Total Service' },
            { selector: '#section-about h2', text: 'Кто я' },
            { selector: '#section-about .section-subtitle', html: 'Я&nbsp;— SMM-специалист и&nbsp;контент-креатор на&nbsp;Северном Кипре. Работаю с&nbsp;премиум-недвижимостью: агентствами, застройщиками и&nbsp;владельцами объектов. Фокус&nbsp;— не&nbsp;«просто посты», а&nbsp;контент и&nbsp;реклама, которые приводят заявки на&nbsp;просмотр, аренду и&nbsp;продажу.' },
            { selector: '#section-about li:nth-of-type(2) span', html: 'Meta Ads и&nbsp;TikTok Ads под лиды и&nbsp;сообщения' },
            { selector: '#section-about li:nth-of-type(3) span', html: 'Съёмка на&nbsp;объекте + монтаж + запуск в&nbsp;одном цикле' },
            { selector: '#section-about img', attrs: { alt: 'Рабочее место SMM: камера, смартфон и аналитика' } },
            { selector: '#section-benefits h2', text: 'Почему это выгодно вам' },
            { selector: '#section-benefits .section-subtitle', html: 'Вместо команды из&nbsp;3–4&nbsp;человек (съёмщик + монтажёр + таргетолог + контент-менеджер) вы&nbsp;получаете:' },
            { selector: '#section-benefits article:nth-of-type(1) .tag', text: 'Под ключ' },
            { selector: '#section-benefits article:nth-of-type(1) h3', text: 'Одного специалиста' },
            { selector: '#section-benefits article:nth-of-type(1) p', html: 'Единый стиль контента и&nbsp;стратегии - без разрозненных подрядчиков и&nbsp;потери фирменного стиля.' },
            { selector: '#section-benefits article:nth-of-type(2) .tag', text: 'Скорость' },
            { selector: '#section-benefits article:nth-of-type(2) h3', text: 'Быстрый цикл' },
            { selector: '#section-benefits article:nth-of-type(2) p', html: 'Снял → смонтировал → запустил рекламу. Минимум согласований и&nbsp;максимум скорости выхода контента.' },
            { selector: '#section-benefits article:nth-of-type(3) .tag', text: 'Экономия' },
            { selector: '#section-benefits article:nth-of-type(3) h3', text: 'Меньше затрат' },
            { selector: '#section-benefits article:nth-of-type(3) p', html: 'Пакет «Контент&nbsp;+&nbsp;Реклама» за&nbsp;1000&nbsp;£ заменяет команду из&nbsp;3–4&nbsp;специалистов и&nbsp;сразу работает на&nbsp;заявки.' },
            { selector: '#section-portfolio h2', text: 'Форматы контента' },
            { selector: '#section-portfolio .section-subtitle', html: 'То, что реально работает для недвижимости в&nbsp;коротких видео' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(1) p', html: 'Обзор апартаментов от&nbsp;входа до&nbsp;вида' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(2) p', html: 'Жизнь на&nbsp;Кипре, локации, атмосфера' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(3) p', html: 'Цена, условия, призыв написать' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) .stat-pill__value', text: 'UGC-стиль' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) p', html: 'Живой кадр в&nbsp;кадре - выше доверие' },
            { selector: '#section-gallery h2', text: 'Примеры роликов' },
            { selector: '#section-gallery .section-subtitle', html: 'Свайпайте галерею и&nbsp;открывайте видео на&nbsp;полный экран' },
            { selector: '#section-system h2', html: 'Что входит в&nbsp;систему продвижения' },
            { selector: '#section-system .section-subtitle', html: 'Полный цикл: от&nbsp;съёмки контента до&nbsp;лидогенерации и&nbsp;аналитики' },
            { selector: '#section-system article:nth-of-type(1) h3', text: 'Контент-продакшн' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(1) span', html: 'съёмка апартаментов / комплексов' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(2) span', html: 'сценарии под аренду и&nbsp;продажи' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(3) span', html: 'монтаж вирусных коротких видео' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(4) span', html: 'адаптация под TikTok / Reels / Shorts' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(5) span', html: 'визуальный стиль под премиум-недвижимость' },
            { selector: '#section-system article:nth-of-type(2) h3', text: 'Социальные сети' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(1) span', html: 'ведение Instagram / TikTok' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(2) span', html: 'оформление профиля под заявки' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(3) span', html: 'регулярный контент-план' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(4) span', html: 'публикации и&nbsp;сторис-стратегия' },
            { selector: '#section-system article:nth-of-type(3) h3', html: 'Реклама и&nbsp;лидогенерация' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(1) span', html: 'настройка Meta Ads / TikTok Ads' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(2) span', html: 'тестирование аудиторий (туристы / аренда / релокация)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(3) span', html: 'оптимизация под заявки (лиды / сообщения / бронирования)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(4) span', html: 'аналитика эффективности' },
            { selector: '#section-process h2', text: 'Как работаем' },
            { selector: '#section-process .section-subtitle', html: 'Прозрачный процесс от&nbsp;первого созвона до&nbsp;отчёта по&nbsp;заявкам' },
            { selector: '#section-process li:nth-of-type(1) h3', text: 'Бриф' },
            { selector: '#section-process li:nth-of-type(1) p', html: 'Цели, объекты, аудитория, доступы к&nbsp;аккаунтам и&nbsp;рекламным кабинетам.' },
            { selector: '#section-process li:nth-of-type(2) h3', text: 'Съёмка' },
            { selector: '#section-process li:nth-of-type(2) p', html: 'Выезд на&nbsp;объекты, сценарии под аренду/продажу, пакет сырья на&nbsp;месяц.' },
            { selector: '#section-process li:nth-of-type(3) h3', text: 'Запуск' },
            { selector: '#section-process li:nth-of-type(3) p', html: 'Монтаж, публикации, запуск рекламы и&nbsp;тесты креативов.' },
            { selector: '#section-process li:nth-of-type(4) h3', text: 'Отчёт' },
            { selector: '#section-process li:nth-of-type(4) p', html: 'Метрики, стоимость лида, выводы и&nbsp;план на&nbsp;следующий цикл.' },
            { selector: '#section-packages .tag.tag--bright.mx-auto', text: 'Выгоднее с рекламой' },
            { selector: '#section-packages h2', text: 'Пакеты сотрудничества' },
            { selector: '#section-packages .section-subtitle', html: 'Базовый пакет&nbsp;— только контент. Для заявок на&nbsp;просмотр и&nbsp;бронь выгоднее второй или третий пакет: там реклама, аналитика и&nbsp;работа на&nbsp;лиды.' },
            { selector: '#section-packages .package-callout', html: '<strong class="text-white">90% клиентов</strong> выбирают «Контент&nbsp;+&nbsp;Реклама» или «Система продаж»&nbsp;— контент без таргета редко окупается в&nbsp;недвижимости.' },
            { selector: '#section-packages article:nth-of-type(1) .tag', text: 'Только контент' },
            { selector: '#section-packages article:nth-of-type(1) p.text-xs', html: 'Подходит, если нужны ролики без рекламы. Заявки и&nbsp;таргет не&nbsp;входят.' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(1) span', html: 'контент-стратегия' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(2) span', html: 'съёмка контента' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(3) span', html: '12–15&nbsp;видео в&nbsp;месяц' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(4) span', html: '70%&nbsp;— короткие видео до&nbsp;15–20&nbsp;секунд' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(5) span', html: '30%&nbsp;— полные обзоры до&nbsp;1&nbsp;минуты' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(6) span', html: 'базовое ведение соцсетей' },
            { selector: '#section-packages article:nth-of-type(1) .btn-outline', text: 'Только контент' },
            { selector: '#section-packages article:nth-of-type(2) .tag', text: 'Рекомендуем · лучший выбор' },
            { selector: '#section-packages article:nth-of-type(2) p.text-accent', html: '+300&nbsp;£ к&nbsp;базовому&nbsp;— но&nbsp;с&nbsp;рекламой, заявками и&nbsp;аналитикой' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(1) span', html: 'всё из&nbsp;базового пакета' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(2) span', html: '12–15&nbsp;видео в&nbsp;месяц' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(3) span', html: '50%&nbsp;— короткие видео до&nbsp;15–20&nbsp;секунд' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(4) span', html: '50%&nbsp;— полные обзоры до&nbsp;1&nbsp;минуты' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(5) span', html: 'настройка рекламы Meta Ads' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(6) span', html: 'ведение рекламных кампаний' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(7) span', html: 'тестирование креативов' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(8) span', html: 'работа на&nbsp;заявки и&nbsp;аналитика' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(9) span', html: 'ответы на&nbsp;комментарии' },
            { selector: '#section-packages article:nth-of-type(2) .btn-primary', text: 'Выбрать — выгоднее всего' },
            { selector: '#section-packages article:nth-of-type(3) .tag', text: 'Максимум заявок' },
            { selector: '#section-packages article:nth-of-type(3) p.text-coral-soft', html: 'Для агентств, застройщиков и&nbsp;нескольких объектов' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(1) span', html: 'всё из&nbsp;пакета «Контент&nbsp;+&nbsp;Реклама»' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(2) span', html: '15+&nbsp;роликов в&nbsp;месяц' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(3) span', html: '50%&nbsp;— короткие видео до&nbsp;15–20&nbsp;секунд' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(4) span', html: '50%&nbsp;— полные обзоры до&nbsp;1&nbsp;минуты' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(5) span', html: 'ежедневная работа с&nbsp;контентом и&nbsp;рекламой' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(6) span', html: 'оптимизация под стоимость лида' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(7) span', html: 'стратегия под загрузку объектов' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(8) span', html: 'масштабирование заявок' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(9) span', html: 'ответы в&nbsp;директ' },
            { selector: '#section-packages article:nth-of-type(3) .btn-primary', text: 'Выбрать премиум' },
            { selector: '#section-packages > div > p.text-slate-400', html: 'Рекламный бюджет оплачивается отдельно и&nbsp;не&nbsp;входит в&nbsp;стоимость пакета.' },
            { selector: '#section-extra h2', text: 'Дополнительные услуги' },
            { selector: '#section-extra article:nth-of-type(1) h3', text: 'Актёрское участие' },
            { selector: '#section-extra article:nth-of-type(1) p.text-slate-300', html: 'Сценарии, съёмка, монтаж. Живое присутствие в&nbsp;кадре повышает конверсию в&nbsp;аренду.' },
            { selector: '#section-extra article:nth-of-type(2) h3', html: 'Ролик по&nbsp;запросу' },
            { selector: '#section-extra article:nth-of-type(2) p.text-slate-300', html: 'Анализ идеи, подбор формата, сценарий, съёмка и&nbsp;монтаж.' },
            { selector: '#section-extra article:nth-of-type(3) p.text-slate-300', html: 'Настройка кабинета, запуск кампаний, тестирование креативов и&nbsp;аудиторий.' },
            { selector: '#section-extra article:nth-of-type(4) h3', html: 'Доп. площадки' },
            { selector: '#section-extra article:nth-of-type(4) li:nth-of-type(4)', html: 'Telegram — по&nbsp;запросу' },
            { selector: '#section-extra article.card-featured .tag', text: 'Масштабирование' },
            { selector: '#section-extra article.card-featured h3', text: 'Лидогенерация' },
            { selector: '#section-extra article.card-featured li:nth-of-type(1) span', html: 'выстраивание воронки заявок' },
            { selector: '#section-extra article.card-featured li:nth-of-type(2) span', html: 'оптимизация под бронирования' },
            { selector: '#section-extra article.card-featured li:nth-of-type(3) span', html: 'создание и&nbsp;тестирование креативов' },
            { selector: '#section-extra article.card-featured li:nth-of-type(4) span', html: 'снижение стоимости лида и&nbsp;отчётность' },
            { selector: '#section-extra article.card-featured li:nth-of-type(5) span', html: 'перевод клиентов в&nbsp;Telegram' },
            { selector: '#section-faq h2', text: 'Частые вопросы' },
            { selector: '#section-faq details:nth-of-type(1) summary', text: 'Какой пакет выгоднее?' },
            { selector: '#section-faq details:nth-of-type(1) p', html: 'Базовый «Контент» (700&nbsp;£)&nbsp;— только ролики и&nbsp;ведение соцсетей, без рекламы и&nbsp;заявок. Для недвижимости окупается редко. <strong class="text-white">«Контент&nbsp;+&nbsp;Реклама»</strong> (1000&nbsp;£)&nbsp;— лучший баланс: за&nbsp;+300&nbsp;£ вы&nbsp;получаете таргет, лиды и&nbsp;аналитику. <strong class="text-white">«Система продаж»</strong> (1300&nbsp;£)&nbsp;— если несколько объектов, нужен ежедневный контроль, масштабирование броней и&nbsp;больше роликов в&nbsp;месяц.' },
            { selector: '#section-faq details:nth-of-type(2) summary', html: 'Рекламный бюджет входит в&nbsp;пакет?' },
            { selector: '#section-faq details:nth-of-type(2) p', html: 'Нет. Стоимость пакета&nbsp;— работа специалиста. Бюджет на&nbsp;Meta / TikTok Ads оплачивается отдельно и&nbsp;согласовывается под ваши цели.' },
            { selector: '#section-faq details:nth-of-type(3) summary', html: 'С&nbsp;какого срока лучше начинать?' },
            { selector: '#section-faq details:nth-of-type(3) p', html: 'Оптимально от&nbsp;1–2&nbsp;месяцев: успеваем снять контент, протестировать креативы и&nbsp;настроить воронку заявок. Разовые ролики тоже возможны.' },
            { selector: '#section-faq details:nth-of-type(4) summary', html: 'Что нужно от&nbsp;вас для старта?' },
            { selector: '#section-faq details:nth-of-type(4) p', html: 'Доступы к&nbsp;соцсетям (или права редактора), доступ к&nbsp;рекламному кабинету, список объектов и&nbsp;короткий бриф по&nbsp;целевой аудитории.' },
            { selector: '#section-faq details:nth-of-type(5) summary', html: 'Работаете только с&nbsp;Instagram?' },
            { selector: '#section-faq details:nth-of-type(5) p', html: 'База пакетов&nbsp;— Instagram. TikTok, Facebook, YouTube Shorts и&nbsp;Telegram подключаются как дополнительные площадки.' },
            { selector: '#section-faq details:nth-of-type(6) summary', text: 'Как часто приходят отчёты?' },
            { selector: '#section-faq details:nth-of-type(6) p', html: 'По&nbsp;рекламным пакетам&nbsp;— регулярная аналитика по&nbsp;лидам и&nbsp;стоимости заявки, плюс итог за&nbsp;месяц с&nbsp;выводами и&nbsp;планом.' },
            { selector: '#section-contact h2', text: 'Обсудим ваш проект' },
            { selector: '#section-contact .section-subtitle', html: 'Напишите&nbsp;— отвечу в&nbsp;течение рабочего дня и&nbsp;подберу пакет с&nbsp;рекламой под ваши объекты' },
            { selector: '#section-contact li:nth-of-type(2) .font-semibold', text: '@cyprustotalservice — Telegram' },
            { selector: '#section-contact .surface-panel h3', text: 'Форма заявки временно скрыта' },
            { selector: '#section-contact .surface-panel p', text: 'Пока можно связаться напрямую через Telegram или по email. Отвечу в течение рабочего дня.' },
            { selector: '#section-contact .surface-panel .btn-primary', text: 'Написать в Telegram' },
            { selector: '#section-contact .surface-panel .btn-outline', text: 'Написать на email' },
            { selector: 'footer > div > p', html: '&copy; 2026 Cyprus Total Service — SMM. Все права защищены.' },
            { selector: 'footer nav', attrs: { 'aria-label': 'Навигация в подвале' } },
            { selector: 'footer a[href="#section-about"]', text: 'Кто я' },
            { selector: 'footer a[href="#section-packages"]', text: 'Пакеты' },
            { selector: 'footer a[href="#section-faq"]', text: 'FAQ' },
            { selector: 'footer a[href="#section-contact"]', text: 'Контакты' },
        ],
    },
    en: {
        lang: 'en',
        title: 'Cyprus Total Service — SMM | Northern Cyprus',
        description: 'SMM for premium real estate in Northern Cyprus: filming, Reels/TikTok, Meta Ads, and leads for viewings and bookings.',
        ogTitle: 'Cyprus Total Service — SMM | Northern Cyprus',
        ogDescription: 'Content, ads, and leads for premium real estate in Northern Cyprus. Filming, editing, social media management, and targeting.',
        nodes: [
            { selector: 'nav', attrs: { 'aria-label': 'Main navigation' } },
            { selector: '[data-lang-switcher]', attrs: { 'aria-label': 'Language switcher' } },
            { selector: '[data-nav-toggle]', attrs: { 'aria-label': 'Open menu' } },
            { selector: '[data-nav-menu] a[href="#section-about"]', text: 'About' },
            { selector: '[data-nav-menu] a[href="#section-portfolio"]', text: 'Formats' },
            { selector: '[data-nav-menu] a[href="#section-gallery"]', text: 'Videos' },
            { selector: '[data-nav-menu] a[href="#section-system"]', text: 'Services' },
            { selector: '[data-nav-menu] a[href="#section-packages"]', text: 'Packages' },
            { selector: '[data-nav-menu] a[href="#section-faq"]', text: 'FAQ' },
            { selector: '[data-nav-menu] a[href="#section-contact"]', text: 'Contact' },
            { selector: 'header .leading-tight > span:first-child', text: 'Cyprus Total Service | SMM' },
            { selector: 'header .leading-tight > span:last-child', text: 'SMM · Northern Cyprus' },
            { selector: '#section-main .tag', text: 'Cyprus Total Service · SMM' },
            { selector: '#section-main h1 span:first-child', text: 'Leads for viewings and bookings' },
            { selector: '#section-main h1 span:last-child', text: 'through short-form content and ads in Northern Cyprus' },
            { selector: '#section-main p.text-lg', text: 'Property filming, editing for Reels / TikTok / Shorts, social media management, and Meta ads. One specialist instead of a 3-4 person team, from content to leads.' },
            { selector: '#section-main .btn-primary', text: 'Ad packages' },
            { selector: '#section-main .btn-outline', text: 'Discuss your project' },
            { selector: '#section-main .mt-4.text-sm.text-slate-400', text: 'For viewing and booking leads, the "Content + Ads" or "Sales System" packages work best.' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .stat-pill__value', text: 'Content' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .text-slate-400', text: 'filming and editing' },
            { selector: '#section-main .stat-pill:nth-of-type(2) .stat-pill__value', text: 'Ads' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .stat-pill__value', text: 'Leads' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .text-slate-400', text: 'leads and bookings' },
            { selector: '#section-main img[alt*="Премиум-вилла"]', attrs: { alt: 'Luxury villa filmed for Reels and TikTok' } },
            { selector: '#section-about .tag', text: 'Victoria · Cyprus Total Service' },
            { selector: '#section-about h2', text: 'About me' },
            { selector: '#section-about .section-subtitle', text: 'I am an SMM specialist and content creator in Northern Cyprus. I work with premium real estate: agencies, developers, and property owners. The focus is not just on posting, but on content and ads that generate viewing, rental, and sales leads.' },
            { selector: '#section-about li:nth-of-type(2) span', text: 'Meta Ads and TikTok Ads for leads and messages' },
            { selector: '#section-about li:nth-of-type(3) span', text: 'On-site filming + editing + launch in one cycle' },
            { selector: '#section-about img', attrs: { alt: 'SMM workspace with camera, smartphone, and analytics' } },
            { selector: '#section-benefits h2', text: 'Why this is profitable for you' },
            { selector: '#section-benefits .section-subtitle', text: 'Instead of a 3-4 person team (videographer + editor + media buyer + content manager), you get:' },
            { selector: '#section-benefits article:nth-of-type(1) .tag', text: 'Turnkey' },
            { selector: '#section-benefits article:nth-of-type(1) h3', text: 'One specialist' },
            { selector: '#section-benefits article:nth-of-type(1) p', text: 'One consistent content and strategy style, without scattered contractors and without losing brand identity.' },
            { selector: '#section-benefits article:nth-of-type(2) .tag', text: 'Speed' },
            { selector: '#section-benefits article:nth-of-type(2) h3', text: 'Fast cycle' },
            { selector: '#section-benefits article:nth-of-type(2) p', text: 'Shoot → edit → launch ads. Minimal approvals and maximum speed to market.' },
            { selector: '#section-benefits article:nth-of-type(3) .tag', text: 'Savings' },
            { selector: '#section-benefits article:nth-of-type(3) h3', text: 'Lower costs' },
            { selector: '#section-benefits article:nth-of-type(3) p', text: 'The "Content + Ads" package for 1000 £ replaces a 3-4 person team and starts working for leads immediately.' },
            { selector: '#section-portfolio h2', text: 'Content formats' },
            { selector: '#section-portfolio .section-subtitle', text: 'What really works for real estate in short-form video' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(1) p', text: 'Apartment tour from entrance to view' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(2) p', text: 'Life in Cyprus, locations, atmosphere' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(3) p', text: 'Price, terms, and call to action' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) .stat-pill__value', text: 'UGC style' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) p', text: 'Human presence on camera builds more trust' },
            { selector: '#section-gallery h2', text: 'Video examples' },
            { selector: '#section-gallery .section-subtitle', text: 'Swipe the gallery and open videos fullscreen' },
            { selector: '#section-system h2', text: 'What is included in the promotion system' },
            { selector: '#section-system .section-subtitle', text: 'The full cycle: from content production to lead generation and analytics' },
            { selector: '#section-system article:nth-of-type(1) h3', text: 'Content production' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(1) span', text: 'filming apartments and complexes' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(2) span', text: 'scripts for rentals and sales' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(3) span', text: 'editing viral short-form videos' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(4) span', text: 'adaptation for TikTok / Reels / Shorts' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(5) span', text: 'visual style for premium real estate' },
            { selector: '#section-system article:nth-of-type(2) h3', text: 'Social media' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(1) span', text: 'Instagram / TikTok management' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(2) span', text: 'profile setup for lead generation' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(3) span', text: 'ongoing content plan' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(4) span', text: 'publishing and story strategy' },
            { selector: '#section-system article:nth-of-type(3) h3', text: 'Advertising and lead generation' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(1) span', text: 'Meta Ads / TikTok Ads setup' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(2) span', text: 'audience testing (tourists / rentals / relocation)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(3) span', text: 'optimization for leads (messages / bookings)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(4) span', text: 'performance analytics' },
            { selector: '#section-process h2', text: 'How we work' },
            { selector: '#section-process .section-subtitle', text: 'A transparent process from the first call to lead reporting' },
            { selector: '#section-process li:nth-of-type(1) h3', text: 'Brief' },
            { selector: '#section-process li:nth-of-type(1) p', text: 'Goals, properties, audience, access to accounts and ad managers.' },
            { selector: '#section-process li:nth-of-type(2) h3', text: 'Filming' },
            { selector: '#section-process li:nth-of-type(2) p', text: 'On-site shooting, scripts for rental/sales, and a month-long stock of source material.' },
            { selector: '#section-process li:nth-of-type(3) h3', text: 'Launch' },
            { selector: '#section-process li:nth-of-type(3) p', text: 'Editing, publishing, ad launch, and creative testing.' },
            { selector: '#section-process li:nth-of-type(4) h3', text: 'Report' },
            { selector: '#section-process li:nth-of-type(4) p', text: 'Metrics, cost per lead, conclusions, and plan for the next cycle.' },
            { selector: '#section-packages .tag.tag--bright.mx-auto', text: 'Better with ads' },
            { selector: '#section-packages h2', text: 'Packages' },
            { selector: '#section-packages .section-subtitle', text: 'The basic package is content only. For viewing and booking leads, the second or third package works better because it includes ads, analytics, and lead generation.' },
            { selector: '#section-packages .package-callout', html: '<strong class="text-white">90% of clients</strong> choose "Content + Ads" or "Sales System" - content without paid traffic rarely pays off in real estate.' },
            { selector: '#section-packages article:nth-of-type(1) .tag', text: 'Content only' },
            { selector: '#section-packages article:nth-of-type(1) p.text-xs', text: 'Best if you only need videos without ads. Leads and targeting are not included.' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(1) span', text: 'content strategy' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(2) span', text: 'content shooting' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(3) span', text: '12-15 videos per month' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(4) span', text: '70% short videos up to 15-20 seconds' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(5) span', text: '30% full tours up to 1 minute' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(6) span', text: 'basic social media management' },
            { selector: '#section-packages article:nth-of-type(1) .btn-outline', text: 'Content only' },
            { selector: '#section-packages article:nth-of-type(2) .tag', text: 'Recommended · best value' },
            { selector: '#section-packages article:nth-of-type(2) p.text-accent', html: '+300&nbsp;£ over the base package - but with ads, leads, and analytics' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(1) span', text: 'everything from the base package' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(2) span', text: '12-15 videos per month' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(3) span', text: '50% short videos up to 15-20 seconds' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(4) span', text: '50% full tours up to 1 minute' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(5) span', text: 'Meta Ads setup' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(6) span', text: 'campaign management' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(7) span', text: 'creative testing' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(8) span', text: 'lead generation and analytics' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(9) span', text: 'comment replies' },
            { selector: '#section-packages article:nth-of-type(2) .btn-primary', text: 'Choose best value' },
            { selector: '#section-packages article:nth-of-type(3) .tag', text: 'Maximum leads' },
            { selector: '#section-packages article:nth-of-type(3) p.text-coral-soft', text: 'For agencies, developers, and multiple properties' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(1) span', text: 'everything from the "Content + Ads" package' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(2) span', text: '15+ videos per month' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(3) span', text: '50% short videos up to 15-20 seconds' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(4) span', text: '50% full tours up to 1 minute' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(5) span', text: 'daily work with content and ads' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(6) span', text: 'cost-per-lead optimization' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(7) span', text: 'occupancy strategy' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(8) span', text: 'lead scaling' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(9) span', text: 'direct message replies' },
            { selector: '#section-packages article:nth-of-type(3) .btn-primary', text: 'Choose premium' },
            { selector: '#section-packages > div > p.text-slate-400', text: 'Ad budget is paid separately and is not included in the package price.' },
            { selector: '#section-extra h2', text: 'Additional services' },
            { selector: '#section-extra article:nth-of-type(1) h3', text: 'On-camera appearance' },
            { selector: '#section-extra article:nth-of-type(1) p.text-slate-300', text: 'Script, filming, and editing. A real person on camera improves rental conversion.' },
            { selector: '#section-extra article:nth-of-type(2) h3', text: 'Video on demand' },
            { selector: '#section-extra article:nth-of-type(2) p.text-slate-300', text: 'Idea analysis, format selection, script, filming, and editing.' },
            { selector: '#section-extra article:nth-of-type(3) p.text-slate-300', text: 'Account setup, campaign launch, and creative and audience testing.' },
            { selector: '#section-extra article:nth-of-type(4) h3', text: 'Extra platforms' },
            { selector: '#section-extra article:nth-of-type(4) li:nth-of-type(4)', text: 'Telegram — on request' },
            { selector: '#section-extra article.card-featured .tag', text: 'Scaling' },
            { selector: '#section-extra article.card-featured h3', text: 'Lead generation' },
            { selector: '#section-extra article.card-featured li:nth-of-type(1) span', text: 'lead funnel setup' },
            { selector: '#section-extra article.card-featured li:nth-of-type(2) span', text: 'booking optimization' },
            { selector: '#section-extra article.card-featured li:nth-of-type(3) span', text: 'creative production and testing' },
            { selector: '#section-extra article.card-featured li:nth-of-type(4) span', text: 'lower CPL and reporting' },
            { selector: '#section-extra article.card-featured li:nth-of-type(5) span', text: 'moving clients to Telegram' },
            { selector: '#section-faq h2', text: 'FAQ' },
            { selector: '#section-faq details:nth-of-type(1) summary', text: 'Which package is more profitable?' },
            { selector: '#section-faq details:nth-of-type(1) p', html: 'The basic "Content" package (700&nbsp;£) covers videos and social media only, without ads or leads. In real estate, it rarely pays off. <strong class="text-white">"Content + Ads"</strong> (1000&nbsp;£) is the best balance: for +300&nbsp;£ you get targeting, leads, and analytics. <strong class="text-white">"Sales System"</strong> (1300&nbsp;£) fits cases with multiple properties, daily supervision, booking scale-up, and a higher number of videos per month.' },
            { selector: '#section-faq details:nth-of-type(2) summary', text: 'Is the ad budget included?' },
            { selector: '#section-faq details:nth-of-type(2) p', text: 'No. The package price covers specialist work. Meta / TikTok Ads budget is paid separately and aligned with your goals.' },
            { selector: '#section-faq details:nth-of-type(3) summary', text: 'What is the best starting term?' },
            { selector: '#section-faq details:nth-of-type(3) p', text: 'Ideally 1-2 months: enough time to shoot content, test creatives, and build the lead funnel. One-off videos are also possible.' },
            { selector: '#section-faq details:nth-of-type(4) summary', text: 'What do you need from us to start?' },
            { selector: '#section-faq details:nth-of-type(4) p', text: 'Access to social accounts (or editor rights), access to the ad account, a list of properties, and a short target audience brief.' },
            { selector: '#section-faq details:nth-of-type(5) summary', text: 'Do you work only with Instagram?' },
            { selector: '#section-faq details:nth-of-type(5) p', text: 'Instagram is the base platform. TikTok, Facebook, YouTube Shorts, and Telegram can be added as extra channels.' },
            { selector: '#section-faq details:nth-of-type(6) summary', text: 'How often do reports come?' },
            { selector: '#section-faq details:nth-of-type(6) p', text: 'For ad packages, you get regular analytics on leads and cost per lead, plus a monthly summary with conclusions and a plan.' },
            { selector: '#section-contact h2', text: 'Let us discuss your project' },
            { selector: '#section-contact .section-subtitle', text: 'Message me and I will reply during the working day and suggest the right ad package for your properties.' },
            { selector: '#section-contact li:nth-of-type(2) .font-semibold', text: '@cyprustotalservice — Telegram' },
            { selector: '#section-contact .surface-panel h3', text: 'Application form is temporarily hidden' },
            { selector: '#section-contact .surface-panel p', text: 'For now, you can contact me directly via Telegram or email. I will reply during the working day.' },
            { selector: '#section-contact .surface-panel .btn-primary', text: 'Write on Telegram' },
            { selector: '#section-contact .surface-panel .btn-outline', text: 'Write by email' },
            { selector: 'footer > div > p', html: '&copy; 2026 Cyprus Total Service — SMM. All rights reserved.' },
            { selector: 'footer nav', attrs: { 'aria-label': 'Footer navigation' } },
            { selector: 'footer a[href="#section-about"]', text: 'About' },
            { selector: 'footer a[href="#section-packages"]', text: 'Packages' },
            { selector: 'footer a[href="#section-faq"]', text: 'FAQ' },
            { selector: 'footer a[href="#section-contact"]', text: 'Contact' },
        ],
    },
    tr: {
        lang: 'tr',
        title: 'Cyprus Total Service — SMM | Kuzey Kibris',
        description: 'Kuzey Kibris\'ta premium gayrimenkul icin SMM: cekim, Reels/TikTok, Meta Ads ve gezdirme ile rezervasyon icin leadler.',
        ogTitle: 'Cyprus Total Service — SMM | Kuzey Kibris',
        ogDescription: 'Kuzey Kibris\'taki premium gayrimenkuller icin icerik, reklam ve lead uretimi. Cekim, kurgu, sosyal medya yonetimi ve hedefleme.',
        nodes: [
            { selector: 'nav', attrs: { 'aria-label': 'Ana gezinme' } },
            { selector: '[data-lang-switcher]', attrs: { 'aria-label': 'Dil degistirici' } },
            { selector: '[data-nav-toggle]', attrs: { 'aria-label': 'Menuyu ac' } },
            { selector: '[data-nav-menu] a[href="#section-about"]', text: 'Hakkimda' },
            { selector: '[data-nav-menu] a[href="#section-portfolio"]', text: 'Formatlar' },
            { selector: '[data-nav-menu] a[href="#section-gallery"]', text: 'Videolar' },
            { selector: '[data-nav-menu] a[href="#section-system"]', text: 'Hizmetler' },
            { selector: '[data-nav-menu] a[href="#section-packages"]', text: 'Paketler' },
            { selector: '[data-nav-menu] a[href="#section-faq"]', text: 'SSS' },
            { selector: '[data-nav-menu] a[href="#section-contact"]', text: 'Iletisim' },
            { selector: 'header .leading-tight > span:first-child', text: 'Cyprus Total Service | SMM' },
            { selector: 'header .leading-tight > span:last-child', text: 'SMM · Kuzey Kibris' },
            { selector: '#section-main .tag', text: 'Cyprus Total Service · SMM' },
            { selector: '#section-main h1 span:first-child', text: 'Goruntuleme ve rezervasyon leadleri' },
            { selector: '#section-main h1 span:last-child', text: 'Kuzey Kibris\'ta kisa video icerikleri ve reklam ile' },
            { selector: '#section-main p.text-lg', text: 'Mulk cekimi, Reels / TikTok / Shorts kurgusu, sosyal medya yonetimi ve Meta reklamlari. Icerikten leade kadar 3-4 kisilik ekip yerine tek uzman.' },
            { selector: '#section-main .btn-primary', text: 'Reklamli paketler' },
            { selector: '#section-main .btn-outline', text: 'Projeyi goruselim' },
            { selector: '#section-main .mt-4.text-sm.text-slate-400', text: 'Goruntuleme ve rezervasyon leadleri icin en iyi sonuc "Icerik + Reklam" veya "Satis Sistemi" paketlerinde gelir.' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .stat-pill__value', text: 'Icerik' },
            { selector: '#section-main .stat-pill:nth-of-type(1) .text-slate-400', text: 'cekim ve kurgu' },
            { selector: '#section-main .stat-pill:nth-of-type(2) .stat-pill__value', text: 'Reklam' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .stat-pill__value', text: 'Leadler' },
            { selector: '#section-main .stat-pill:nth-of-type(3) .text-slate-400', text: 'lead ve rezervasyonlar' },
            { selector: '#section-main img[alt*="Премиум-вилла"]', attrs: { alt: 'Reels ve TikTok icin cekilen luks villa' } },
            { selector: '#section-about .tag', text: 'Victoria · Cyprus Total Service' },
            { selector: '#section-about h2', text: 'Ben kimim' },
            { selector: '#section-about .section-subtitle', text: 'Kuzey Kibris\'ta SMM uzmani ve icerik ureticisiyim. Premium gayrimenkul ile calisiyorum: ajanslar, gelistiriciler ve mulk sahipleri. Odagim sadece paylasim yapmak degil; izleme, kiralama ve satis leadleri getiren icerik ve reklamlardir.' },
            { selector: '#section-about li:nth-of-type(2) span', text: 'Lead ve mesaj odakli Meta Ads ve TikTok Ads' },
            { selector: '#section-about li:nth-of-type(3) span', text: 'Tek dongude cekim + kurgu + yayin' },
            { selector: '#section-about img', attrs: { alt: 'Kamera, akilli telefon ve analizlerle SMM calisma alani' } },
            { selector: '#section-benefits h2', text: 'Neden sizin icin avantajli' },
            { selector: '#section-benefits .section-subtitle', text: '3-4 kisilik ekip yerine (videograf + editor + reklam yoneticisi + icerik yoneticisi) sunlari alirsiniz:' },
            { selector: '#section-benefits article:nth-of-type(1) .tag', text: 'Anahtar teslim' },
            { selector: '#section-benefits article:nth-of-type(1) h3', text: 'Tek uzman' },
            { selector: '#section-benefits article:nth-of-type(1) p', text: 'Daginik yukleniciler olmadan, marka stilini kaybetmeden tek elden strateji ve icerik.' },
            { selector: '#section-benefits article:nth-of-type(2) .tag', text: 'Hiz' },
            { selector: '#section-benefits article:nth-of-type(2) h3', text: 'Hizli dongu' },
            { selector: '#section-benefits article:nth-of-type(2) p', text: 'Cek → kurgula → reklami baslat. Minimum onay, maksimum hiz.' },
            { selector: '#section-benefits article:nth-of-type(3) .tag', text: 'Tasarruf' },
            { selector: '#section-benefits article:nth-of-type(3) h3', text: 'Daha dusuk maliyet' },
            { selector: '#section-benefits article:nth-of-type(3) p', text: '"Icerik + Reklam" paketi 1000 £ ile 3-4 kisilik ekibin yerini alir ve hemen lead getirir.' },
            { selector: '#section-portfolio h2', text: 'Icerik formatlari' },
            { selector: '#section-portfolio .section-subtitle', text: 'Kisa videolarda gayrimenkul icin gercekten ise yarayan formatlar' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(1) p', text: 'Giristen manzaraya kadar daire turu' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(2) p', text: 'Kibris yasami, lokasyonlar ve atmosfer' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(3) p', text: 'Fiyat, kosullar ve harekete gecirici mesaj' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) .stat-pill__value', text: 'UGC stil' },
            { selector: '#section-portfolio .stat-pill:nth-of-type(4) p', text: 'Kadrajda insan olmasi guveni artirir' },
            { selector: '#section-gallery h2', text: 'Video ornekleri' },
            { selector: '#section-gallery .section-subtitle', text: 'Galeriyi kaydirin ve videolari tam ekranda acin' },
            { selector: '#section-system h2', text: 'Tanitim sistemine neler dahil' },
            { selector: '#section-system .section-subtitle', text: 'Tam dongu: icerik uretiminden lead toplama ve analitige kadar' },
            { selector: '#section-system article:nth-of-type(1) h3', text: 'Icerik prodaksiyonu' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(1) span', text: 'daire ve proje cekimleri' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(2) span', text: 'kiralama ve satis icin senaryolar' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(3) span', text: 'viral kisa video kurgusu' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(4) span', text: 'TikTok / Reels / Shorts uyarlamasi' },
            { selector: '#section-system article:nth-of-type(1) li:nth-of-type(5) span', text: 'premium gayrimenkule uygun gorsel stil' },
            { selector: '#section-system article:nth-of-type(2) h3', text: 'Sosyal medya' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(1) span', text: 'Instagram / TikTok yonetimi' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(2) span', text: 'lead odakli profil duzeni' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(3) span', text: 'duzenli icerik plani' },
            { selector: '#section-system article:nth-of-type(2) li:nth-of-type(4) span', text: 'paylasim ve hikaye stratejisi' },
            { selector: '#section-system article:nth-of-type(3) h3', text: 'Reklam ve lead uretimi' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(1) span', text: 'Meta Ads / TikTok Ads kurulumu' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(2) span', text: 'hedef kitle testleri (turist / kiralama / tasinma)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(3) span', text: 'lead optimizasyonu (mesaj / rezervasyon)' },
            { selector: '#section-system article:nth-of-type(3) li:nth-of-type(4) span', text: 'performans analitigi' },
            { selector: '#section-process h2', text: 'Nasil calisiyoruz' },
            { selector: '#section-process .section-subtitle', text: 'Ilk gorusmeden lead raporlamasina kadar seffaf surec' },
            { selector: '#section-process li:nth-of-type(1) h3', text: 'Brief' },
            { selector: '#section-process li:nth-of-type(1) p', text: 'Hedefler, mulkler, hedef kitle, hesap ve reklam yoneticisi erisimleri.' },
            { selector: '#section-process li:nth-of-type(2) h3', text: 'Cekim' },
            { selector: '#section-process li:nth-of-type(2) p', text: 'Sahada cekim, kiralama/satis senaryolari ve bir aylik ham icerik paketi.' },
            { selector: '#section-process li:nth-of-type(3) h3', text: 'Yayin' },
            { selector: '#section-process li:nth-of-type(3) p', text: 'Kurgu, paylasim, reklam yayina alma ve kreatif testleri.' },
            { selector: '#section-process li:nth-of-type(4) h3', text: 'Rapor' },
            { selector: '#section-process li:nth-of-type(4) p', text: 'Metrikler, lead maliyeti, cikarimlar ve sonraki dongu plani.' },
            { selector: '#section-packages .tag.tag--bright.mx-auto', text: 'Reklamla daha etkili' },
            { selector: '#section-packages h2', text: 'Is birligi paketleri' },
            { selector: '#section-packages .section-subtitle', text: 'Temel paket sadece icerik icindir. Goruntuleme ve rezervasyon leadleri icin ikinci veya ucuncu paket daha verimlidir; reklam, analiz ve lead toplama dahildir.' },
            { selector: '#section-packages .package-callout', html: '<strong class="text-white">Musterilerin %90\'i</strong> "Icerik + Reklam" veya "Satis Sistemi" paketini seciyor - ucretli trafik olmadan icerik gayrimenkulde nadiren geri donus saglar.' },
            { selector: '#section-packages article:nth-of-type(1) .tag', text: 'Sadece icerik' },
            { selector: '#section-packages article:nth-of-type(1) p.text-xs', text: 'Reklamsiz sadece video istiyorsaniz uygundur. Lead ve hedefleme dahil degildir.' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(1) span', text: 'icerik stratejisi' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(2) span', text: 'icerik cekimi' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(3) span', text: 'ayda 12-15 video' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(4) span', text: '%70 kisa videolar, 15-20 saniyeye kadar' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(5) span', text: '%30 tam daire turlari, 1 dakikaya kadar' },
            { selector: '#section-packages article:nth-of-type(1) li:nth-of-type(6) span', text: 'temel sosyal medya yonetimi' },
            { selector: '#section-packages article:nth-of-type(1) .btn-outline', text: 'Sadece icerik' },
            { selector: '#section-packages article:nth-of-type(2) .tag', text: 'Onerilen · en iyi denge' },
            { selector: '#section-packages article:nth-of-type(2) p.text-accent', html: 'Temel pakete gore +300&nbsp;£ - ama reklam, lead ve analiz dahil' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(1) span', text: 'temel paketteki her sey' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(2) span', text: 'ayda 12-15 video' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(3) span', text: '%50 kisa videolar, 15-20 saniyeye kadar' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(4) span', text: '%50 tam daire turlari, 1 dakikaya kadar' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(5) span', text: 'Meta Ads kurulumu' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(6) span', text: 'kampanya yonetimi' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(7) span', text: 'kreatif testleri' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(8) span', text: 'lead uretimi ve analiz' },
            { selector: '#section-packages article:nth-of-type(2) li:nth-of-type(9) span', text: 'yorum yanitlari' },
            { selector: '#section-packages article:nth-of-type(2) .btn-primary', text: 'En iyi secimi al' },
            { selector: '#section-packages article:nth-of-type(3) .tag', text: 'Maksimum lead' },
            { selector: '#section-packages article:nth-of-type(3) p.text-coral-soft', text: 'Ajanslar, gelistiriciler ve coklu portfoy icin' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(1) span', text: '"Icerik + Reklam" paketindeki her sey' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(2) span', text: 'ayda 15+ video' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(3) span', text: '%50 kisa videolar, 15-20 saniyeye kadar' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(4) span', text: '%50 tam daire turlari, 1 dakikaya kadar' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(5) span', text: 'icerik ve reklamla gunluk calisma' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(6) span', text: 'lead maliyeti optimizasyonu' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(7) span', text: 'doluluk stratejisi' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(8) span', text: 'leadleri olceklendirme' },
            { selector: '#section-packages article:nth-of-type(3) li:nth-of-type(9) span', text: 'DM yanitlari' },
            { selector: '#section-packages article:nth-of-type(3) .btn-primary', text: 'Premium sec' },
            { selector: '#section-packages > div > p.text-slate-400', text: 'Reklam butcesi ayrica odenir ve paket fiyatina dahil degildir.' },
            { selector: '#section-extra h2', text: 'Ek hizmetler' },
            { selector: '#section-extra article:nth-of-type(1) h3', text: 'Kamerada oyuncu / sunucu' },
            { selector: '#section-extra article:nth-of-type(1) p.text-slate-300', text: 'Senaryo, cekim ve kurgu. Kamerada canli insan olmasi kiralama donusumunu artirir.' },
            { selector: '#section-extra article:nth-of-type(2) h3', text: 'Talebe gore video' },
            { selector: '#section-extra article:nth-of-type(2) p.text-slate-300', text: 'Fikir analizi, format secimi, senaryo, cekim ve kurgu.' },
            { selector: '#section-extra article:nth-of-type(3) p.text-slate-300', text: 'Hesap kurulumu, kampanya yayini ve kreatif / kitle testleri.' },
            { selector: '#section-extra article:nth-of-type(4) h3', text: 'Ek platformlar' },
            { selector: '#section-extra article:nth-of-type(4) li:nth-of-type(4)', text: 'Telegram — talebe gore' },
            { selector: '#section-extra article.card-featured .tag', text: 'Olceklendirme' },
            { selector: '#section-extra article.card-featured h3', text: 'Lead uretimi' },
            { selector: '#section-extra article.card-featured li:nth-of-type(1) span', text: 'lead hunisi kurulumu' },
            { selector: '#section-extra article.card-featured li:nth-of-type(2) span', text: 'rezervasyon optimizasyonu' },
            { selector: '#section-extra article.card-featured li:nth-of-type(3) span', text: 'kreatif uretimi ve testleri' },
            { selector: '#section-extra article.card-featured li:nth-of-type(4) span', text: 'daha dusuk lead maliyeti ve raporlama' },
            { selector: '#section-extra article.card-featured li:nth-of-type(5) span', text: 'musterileri Telegram\'a yonlendirme' },
            { selector: '#section-faq h2', text: 'Sik sorulan sorular' },
            { selector: '#section-faq details:nth-of-type(1) summary', text: 'Hangi paket daha avantajli?' },
            { selector: '#section-faq details:nth-of-type(1) p', html: 'Temel "Icerik" paketi (700&nbsp;£) sadece video ve sosyal medya yonetimini kapsar; reklam ve lead yoktur. Gayrimenkulde cogu zaman tek basina yeterli olmaz. <strong class="text-white">"Icerik + Reklam"</strong> (1000&nbsp;£) en dengeli secenektir: +300&nbsp;£ ile hedefleme, lead ve analiz alirsiniz. <strong class="text-white">"Satis Sistemi"</strong> (1300&nbsp;£) ise birden fazla portfoy, gunluk kontrol, rezervasyonlari buyutme ve ayda daha fazla video isteyenler icindir.' },
            { selector: '#section-faq details:nth-of-type(2) summary', text: 'Reklam butcesi pakete dahil mi?' },
            { selector: '#section-faq details:nth-of-type(2) p', text: 'Hayir. Paket ucreti uzmanin hizmet bedelidir. Meta / TikTok Ads butcesi ayrica odenir ve hedeflerinize gore belirlenir.' },
            { selector: '#section-faq details:nth-of-type(3) summary', text: 'En iyi baslangic suresi nedir?' },
            { selector: '#section-faq details:nth-of-type(3) p', text: 'Ideal sure 1-2 aydir: icerik cekimi, kreatif testleri ve lead hunisi kurulumu icin yeterlidir. Tek seferlik videolar da mumkundur.' },
            { selector: '#section-faq details:nth-of-type(4) summary', text: 'Baslangic icin sizden ne gerekir?' },
            { selector: '#section-faq details:nth-of-type(4) p', text: 'Sosyal medya hesap erisimi (veya editor yetkisi), reklam hesabi erisimi, mulk listesi ve kisa bir hedef kitle briefi.' },
            { selector: '#section-faq details:nth-of-type(5) summary', text: 'Sadece Instagram ile mi calisiyorsunuz?' },
            { selector: '#section-faq details:nth-of-type(5) p', text: 'Temel platform Instagram\'dir. TikTok, Facebook, YouTube Shorts ve Telegram ek kanallar olarak eklenebilir.' },
            { selector: '#section-faq details:nth-of-type(6) summary', text: 'Raporlar ne kadar sik gelir?' },
            { selector: '#section-faq details:nth-of-type(6) p', text: 'Reklamli paketlerde lead ve lead maliyeti uzerine duzenli analiz, ayrica ay sonu ozet, cikarimlar ve plan alirsiniz.' },
            { selector: '#section-contact h2', text: 'Projenizi konusalim' },
            { selector: '#section-contact .section-subtitle', text: 'Yazin, is gunu icinde cevap vereyim ve portfoyunuz icin uygun reklam paketini onereyim.' },
            { selector: '#section-contact li:nth-of-type(2) .font-semibold', text: '@cyprustotalservice — Telegram' },
            { selector: '#section-contact .surface-panel h3', text: 'Basvuru formu gecici olarak gizli' },
            { selector: '#section-contact .surface-panel p', text: 'Simdilik Telegram veya e-posta ile dogrudan ulasabilirsiniz. Is gunu icinde cevap veririm.' },
            { selector: '#section-contact .surface-panel .btn-primary', text: 'Telegram\'dan yazin' },
            { selector: '#section-contact .surface-panel .btn-outline', text: 'E-posta gonderin' },
            { selector: 'footer > div > p', html: '&copy; 2026 Cyprus Total Service — SMM. Tum haklari saklidir.' },
            { selector: 'footer nav', attrs: { 'aria-label': 'Altbilgi gezinme' } },
            { selector: 'footer a[href="#section-about"]', text: 'Hakkimda' },
            { selector: 'footer a[href="#section-packages"]', text: 'Paketler' },
            { selector: 'footer a[href="#section-faq"]', text: 'SSS' },
            { selector: 'footer a[href="#section-contact"]', text: 'Iletisim' },
        ],
    },
};

const setNodeContent = (element, config) => {
    if (!element || !config) {
        return;
    }

    if (Object.prototype.hasOwnProperty.call(config, 'html')) {
        element.innerHTML = config.html;
    } else if (Object.prototype.hasOwnProperty.call(config, 'text')) {
        element.textContent = config.text;
    }

    if (config.attrs) {
        Object.keys(config.attrs).forEach((name) => {
            element.setAttribute(name, config.attrs[name]);
        });
    }
};

const languageSwitcher = () => {
    const switcher = document.querySelector('[data-lang-switcher]');
    const buttons = document.querySelectorAll('[data-lang]');

    if (!switcher || !buttons.length) {
        return;
    }

    const metaDescription = document.querySelector('meta[name="description"]');
    const ogTitle = document.querySelector('meta[property="og:title"]');
    const ogDescription = document.querySelector('meta[property="og:description"]');

    const applyLanguage = (language) => {
        const locale = translations[language] ? language : 'ru';
        const translation = translations[locale];

        document.documentElement.lang = translation.lang;
        document.title = translation.title;

        if (metaDescription) {
            metaDescription.setAttribute('content', translation.description);
        }

        if (ogTitle) {
            ogTitle.setAttribute('content', translation.ogTitle);
        }

        if (ogDescription) {
            ogDescription.setAttribute('content', translation.ogDescription);
        }

        translation.nodes.forEach((item) => {
            const element = document.querySelector(item.selector);
            setNodeContent(element, item);
        });

        buttons.forEach((button) => {
            const isActive = button.getAttribute('data-lang') === locale;
            button.classList.toggle('is-active', isActive);
            button.setAttribute('aria-pressed', isActive ? 'true' : 'false');
        });

        window.localStorage.setItem(STORAGE_KEY, locale);
    };

    buttons.forEach((button) => {
        button.addEventListener('click', () => {
            applyLanguage(button.getAttribute('data-lang'));
        });
    });

    applyLanguage(window.localStorage.getItem(STORAGE_KEY) || document.documentElement.lang || 'ru');
};

export default languageSwitcher;
